### ISSUE TITLE
info - array ser/des

### ISSUE THREAD

**Issue by ilteoood** [oramasearch/seqproto#5]
Hi!
Not a real issue, just looking for some info.

Looking at the definition of the `Ser` interface, I see there are 3 different ways to serialize an array:
- serializeArray;
- serializeIterable;
- serializeIndexableArray (this one is never mentioned in the readme)

What is the main difference between them?
Has each a better performance in a specific scenario? If so, can you make an example?

**Comment by allevo** [comment]
Hi!
- serializeArray: serialize an array. the serialization process writes an integer to know the size, and after the items
- serializeIterable: do the same, but keep an iterable. This allows you to serialize Set<T> and Map<K, V> without converting them into an array. This safe memory allocation, therefore, is faster. Anyway, if you have an array, the serializeArray is preferable.
- serializeIndexableArray: serialize an array and allow you to get some elements. For instance, if you need just the first and the 5th, you can deserialize only them using `getArrayElements([0, 4], ...)`. You are right, and this is not documented because it is hard to describe (and probably we can improve the names here).

**Comment by ilteoood** [comment]
On my side, everything you said is clear and we can close this, many thanks for dedicating me some time!
If you prefer, we can keep this open just as reminder about the documentation

**Comment by allevo** [comment]
If you would like to contribute, every tip/PR/suggestion is welcomed!
So, I'm closing this. Thanks for your interest in this project.
